# Base Python image
FROM python:3.12-slim

# Working directory
WORKDIR /app

# environment variable
ENV PYTHONPATH=/app

# Install dependencies
COPY requirements-streamlit.txt .
RUN pip install --no-cache-dir -r requirements-streamlit.txt

# Copy project files
COPY . .

# Start Streamlit
CMD ["sh", "-c", "streamlit run app/streamlit_app.py --server.port=${PORT:-8501} --server.address=0.0.0.0"]